# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 17:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ShortNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('source', models.URLField()),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('featured_for', models.DateTimeField(blank=True, default=None, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('score', models.SmallIntegerField()),
                ('report_count', models.PositiveSmallIntegerField()),
                ('categories', models.ManyToManyField(to='blog.Category')),
            ],
        ),
    ]
