# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170725_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortnews',
            name='report_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shortnews',
            name='score',
            field=models.SmallIntegerField(default=0),
        ),
    ]
