# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170725_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortnews',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
