# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='shortnews',
            options={'get_latest_by': 'created', 'ordering': ['title'], 'verbose_name': 'Short News', 'verbose_name_plural': 'Short News'},
        ),
        migrations.AddField(
            model_name='shortnews',
            name='parent_news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_news', to='blog.ShortNews'),
        ),
    ]
