# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170727_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='shortnews',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
